### ISSUE TITLE
The "User from ID" identity mode serializes as a wrong value ("userId") into function.json.

### ISSUE THREAD

**Issue by yutao-huang** [Azure/azure-functions-microsoftgraph-extension#11]
[Steps]
1. Enable Functions 2.0 preview feature, pick the HTTP Trigger template, install the Microsoft Graph extension;
2. In the Integrate settings page, add the Auth token as a new input;
3. Pick "User From ID" as the Identity mode;
4. Fill in other required fields and click on "Save".

[Expected]
The settings should be saved successfully.

[Actual]
An error message is shown:
Function ($HttpTriggerCSharp1) Error: Could not convert 'userId' to TokenIdentityMode. Error converting value "userId" to type 'Microsoft.Azure.WebJobs.TokenIdentityMode'. Path 'identity'. Requested value 'userId' was not found.

[Note]
Looking into function.json, you will see the identity value is "userId", which is wrong and should be "userFromId".

After manually fixing the function.json to have "userFromId" as the identity mode. Everything works as expected.

**Comment by soninaren** [comment]
fixed in here 
https://github.com/Azure/azure-webjobs-sdk-templates/pull/574
