### ISSUE TITLE
Samples are down

### ISSUE THREAD

**Issue by DDAndyChen** [Azure/azure-functions-microsoftgraph-extension#15]
> The Outlook, OneDrive, and Excel bindings derive from the token binding. See https://github.com/glennamanns/TokenBinding for more information about the token binding.
> These bindings should also integrate with the O365 SDK to provide a full experienc.
>See https://github.com/Azure/MikeBindings/blob/master/Samples/Functions.cs for sample usages.

Are there alternatives?

**Comment by martinpeck** [comment]
Yep. Both of those links result in a 404.

**Comment by mattchenderson** [comment]
That binding is actually in this repo. They were previously separated out. We should probably remove that paragraph.

**Comment by ConnorMcMahon** [comment]
New samples have been merged into master
