### ISSUE TITLE
Docs Don't Contain "How to Contribute" Instructions

### ISSUE THREAD

**Issue by martinpeck** [Azure/azure-functions-microsoftgraph-extension#20]
A suggestion, rather than an issue.

I have a potential PR, but I'm struggling to test my code locally (against one of my Functions). The unit tests run, but I want to see it working against a real function.

The README.md doesn't have any hints on how to set up local dev environment. Even a few hints/bullets might be useful and raise the chances of PRs being useful.

**Comment by ConnorMcMahon** [comment]
This has now been merged into master
