### ISSUE TITLE
Client credentials flow breaking

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-microsoftgraph-extension#25]
If you attempt to use the client credentials flow, you will get an error stating that your application "was not found in the directory microsoft.com." The "microsoft.com" piece will occur no matter what tenant your application is in.

Early guess is that this is due to us using the common endpoint, when a client credentials flow should be against a proper tenant. You can verify this by attempting the flow manually in postman using the common endpoint.

**Comment by ConnorMcMahon** [comment]
This was addressed here `https://github.com/Azure/azure-functions-microsoftgraph-extension/pull/12/files`. Expect in in the next release of functions.

**Comment by ConnorMcMahon** [comment]
This was addressed [here](https://github.com/Azure/azure-functions-microsoftgraph-extension/pull/12/files). Expect in in the next release of functions.

**Comment by TechWatching** [comment]
@ConnorMcMahon Do you when when is the next release planned ? In the meantime do you know a workaround for this ? I need client credentials to use the new outlook azure functions templates.

**Comment by APraestegaard** [comment]
@mattchenderson - you wrote:
> You can verify this by attempting the flow manually in postman using the common endpoint.
I can verify this in Postman using the following configuration:
<img width="408" alt="postman graph client credentials setup" src="https://user-images.githubusercontent.com/21753997/36370126-31e8200e-155e-11e8-90b4-ae647baeeafb.png">

I have a non-azure-functions-related need to call Graph-endpoints and as I understand I need to replace "common" with the tenant id in the Access Token Url: _https://login.microsoftonline.com/common/oauth2/v2.0/token_ (?). Doing so I will get an accesstoken, but the response from the endpoint (https://graph.microsoft.com/v1.0/deviceManagement/managedDevices) using that token is beyond me:
<img width="678" alt="postman graph client credentials error" src="https://user-images.githubusercontent.com/6850753/36370694-f2065972-155f-11e8-8f04-4478ef93f7af.png">

Would you have any advice?
