### ISSUE TITLE
Javascript not supported for Excel Output Bindings

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-microsoftgraph-extension#34]
JavaScript is not properly supported for Excel output bindings in beta1 or beta2. This should be fixed before releasing beta3.

**Comment by lumaxis** [comment]
Just ran into this and am looking forward to this being fixed!

**Comment by ConnorMcMahon** [comment]
This should be addressed by #42, but will validate before closing.

**Comment by ConnorMcMahon** [comment]
Actually addressed by #47
