### ISSUE TITLE
System.IO.FileSystem: Could not find a part of the path 'D:\home\data\byob_graphmap'

### ISSUE THREAD

**Issue by baywet** [Azure/azure-functions-microsoftgraph-extension#38]
By default if you run the examples with the CLI you'll get the error message described in the title.
I feel like the "DefaultBYOBLocation" should be a relative path. Or a least the BYOB_TokenMap key should be documented on the readme to get started.

**Comment by ConnorMcMahon** [comment]
Local development hasn't been a huge push yet due to the large dependency on EasyAuth, which doesn't run well locally (we are hoping to change this in the near future). 

Regardless, this is a quick fix, and I see no reason we can't fix this in the next release.

**Comment by ConnorMcMahon** [comment]
I decided to make the change in the README for now, see #44.
