### ISSUE TITLE
NuGet Package has Incorrect Description

### ISSUE THREAD

**Issue by martinpeck** [Azure/azure-functions-microsoftgraph-extension#41]
The NuGet package for this extension has the following description:

> This extension adds bindings for EventGrid

![image](https://user-images.githubusercontent.com/1524451/37970652-eefdd5ba-31cb-11e8-87b4-1bb4403cb47e.png)

Which is clearly not the case :) 

It means that this package appears in searches for the EventGrid bindings.

**Comment by ConnorMcMahon** [comment]
Thanks for the fix. We will fix this for version 1.0.0-beta3 and on :)

**Comment by ConnorMcMahon** [comment]
Somehow I missed the boat on this release. Moving the milestone to beta4.

**Comment by ConnorMcMahon** [comment]
Fix this in #64
