### ISSUE TITLE
Get graphToken for local development

### ISSUE THREAD

**Issue by fiyazbinhasan** [Azure/azure-functions-microsoftgraph-extension#54]
I followed the steps listed in `local development` section. However, I'm not sure how to get and store a graphToken for local development i.e. running on `localhost` throws 500. What would be the desired configuration for `local.settings.json` file for local development? TIA

**Comment by SebastianSchuetze** [comment]
I made it work for my environment to get the graph token. I just give you my local.settings.json

```json
{
  "Values": {
    "WEBSITE_AUTH_CLIENT_ID": "**clientID**",
    "WEBSITE_AUTH_CLIENT_SECRET": "**clientSecret**",
    "WEBSITE_AUTH_OPENID_ISSUER": "https://sts.windows.net/**IssuerID**"
  }
}
```
just be aware that the **WEBSITE_AUTH_OPENID_ISSUER** needs to be a url and not only the ID of the tenant in azure.

**Comment by fiyazbinhasan** [comment]
@ConnorMcMahon works like a charm! Used the `UserFromRequest` method. Although I think the `WEBSITE_HOSTNAME` is not required since it throws the following message on the console, 

> An item with the same key has already been added. Key: WEBSITE_HOSTNAME

Another thing, can you briefly explain the usage of `BYOB_TokenMap` . Many thanks :)

**Comment by ConnorMcMahon** [comment]
@fiyazbinhasan, `BYOB_TokenMap` is the location that data about Graph webhook subscriptions is stored. Setting it to a local directory in your `local.settings.json` should be sufficient. 

Speaking of Graph webhooks, unfortunately we don't have a good local development story for that yet. Creating a Graph webhook subscription requires the Graph API to hit an exposed endpoint of the Function runtime. Using a tool like ngrok may expose that endpoint properly to the Graph API, but that hasn't been tested yet, and there is likely some development work that would be required to make it work well locally.
