### ISSUE TITLE
Excel Graph bindings are not working if a previous function use Token attribute

### ISSUE THREAD

**Issue by gbarcho** [Azure/azure-functions-microsoftgraph-extension#61]
Playing around with the sdk beta 3 i found that if a previous function use the Token attribute all the bindings defined for Excel doesnt work.

Environment
Azure Functions v2.
Host 2.2.2
SDK: beta 3

Repro steps
- create a function to use the Token attribute.
- example code
```csharp 
public static class Function1
    {

        [FunctionName("Function1")]
        public static async Task<IActionResult> Run1Async(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req,
            [Token(
                        Identity = TokenIdentityMode.UserFromToken,
                        UserToken = "%UserToken%",
                        IdentityProvider = "AAD",
                        Resource = "https://graph.microsoft.com")] string token
        )
        {
            return new OkObjectResult(token);
        }


        [FunctionName("Function2")]
        public static async Task<IActionResult> Run2Async(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req,
            [Excel(
                Path = "some name",
                TableName ="Table1",
                Identity = TokenIdentityMode.UserFromToken,
                UserToken = "%UserToken%",
                IdentityProvider = "AAD",
                Resource = "https://graph.microsoft.com")] string[][] table
            )
        {
            return new OkObjectResult("OK");
        }
    }
```
- This error should be show in the console 
![image](https://user-images.githubusercontent.com/39923760/42186892-98553320-7e24-11e8-9435-0680c84029d0.png)

workaround
- Remove function 1 and should work
![image](https://user-images.githubusercontent.com/39923760/42187133-59eef570-7e25-11e8-9d76-a786fe71f066.png)

I think the issue is related on the order on which the extensions are added because if *function 1* is declared after *function 2* the bindings works

Thanks

**Comment by ConnorMcMahon** [comment]
Interesting bug. This likely is tied to how the functions runtime loads assemblies of extensions. I will investigate this some more.

**Comment by ConnorMcMahon** [comment]
This should be fixed in beta4 that will be released in the next day or so.
