### ISSUE TITLE
Stream type for OneDrive output cannot create files

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-microsoftgraph-extension#8]
If you bind to a stream type and attempt to work with a file that does not yet exist, a "resource not found" error will be thrown. Other binding types can create files.

**Comment by mattchenderson** [comment]
Example functions.json:
```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in"
    },
    {
      "name": "myOneDriveFile",
      "type": "onedrive",
      "direction": "out",
      "path": "{query.filename}",
      "identity": "userFromRequest"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

Example C#:
```
using System.Net;
using System.Text;

public static async Task Run(HttpRequest req, TraceWriter log, Stream myOneDriveFile)
{
    string data = req.Query
        .FirstOrDefault(q => string.Compare(q.Key, "text", true) == 0)
        .Value;
    await myOneDriveFile.WriteAsync(Encoding.UTF8.GetBytes(data), 0, data.Length);
    return;
}
```

**Comment by ConnorMcMahon** [comment]
This is being address in PR #14. Note that this now mimics BlobAttributes. However, we don't quite yet have full parity with Blobs, as the WebJobs SDK has some business logic hardcoded in to set the Access metadata based on the direction of the binding; "in" = "read", "out" = "write". For now, that means that even with the fix in the PR, we will need to manually set the "access" metadata to correspond with the direction.

**Comment by ConnorMcMahon** [comment]
This should be in the next release of Functions 2.0.
